---
title: "Master thesis"
author: "D van Putten"
date: "2024-10-28"
output: html_document
---
# Introduction
As the global population is expected to rise up to 10 billion by the 2080s, ensuring food security has become increasingly more important (United Nations, 2024; Carthy et al., 2018). One of the major challenges of feeding the growing populations is mitigating crop loss due to pests (Oerke & Dehne, 2004).  
One such a major pest is the cotton bollworm or *Helicoverpa armigera*, a polyphagous moth species that feeds on different types of plants. Originally found in Africa, Europe, Asia and Australia, *H. armigera* was first documented in the Americas in Brazil in 2013, but has now spread to many other Latin American countries (see haile page 2). Due to its polyphagous nature, there is a significant threat to many crops, but there is a particular threat to soybean farms (reference haile 2). H. armigera is known to have a rapid resistance development (ref in haile), so finding suitable pest management strategies is of the utmost importance.

Traditionally, synthetic pesticides are used to protect crops, but the widespread use of these synthetic pesticides has led to a rapid evolution of pesticide resistance in pest populations, reducing their long-term effectiveness (see ref in ayilara). The genetic basis underlying the development of resistance to synthetic pesticides usually only involves few genes, allowing pests to adapt more easily and faster and accelerating the spread of resistance in pest populations and undermining pest control strategies (ref in ayilara). 
In recent years, more research has been conducted on the use of biopesticides (natural organisms or substances derived from them) as an alternative and more sustainable pest control strategy in agricultural practices (find articles about research for reference). Biopesticides interact in a more complex way with the pest immune system than synthetic pesticides by often targeting more physiological pathways (ref in ayilara page7). This complexity gives an advantage because resistance developing in pests is usually polygenic, meaning that multiple genes contribute to resistance. This means that resistance to biopesticides is a continuous trait and requires more genetic changes than for synthetic pesticides ( Falconer1981 see via). As a result, the polygenic nature of resistance makes it more challenging for a pest to develop resistance, giving a potential resolution to resistance development (reference, maybe tinsley paper for polygenic, variation?). 

In natural systems, pest populations show genetic variation in traits important for survival such as resistance to pathogens or pesticides (tinsley paper). This variation is likely to be maintained due to gene-by-environment interactions (hereafter GxE), in which genes express differently depending on the environment. GxE can lead to genetic trade-offs between life history traits. For example, in certain environments, pests may allocate resources to survival of infection, but not to reproductive success. (lazarro 2009). Genetic trade-offs are caused by genetic correlations between traits due to pleiotropy, in which one gene affects multiple traits (see reference via).
These trade-off models stem from the life history theory that suggests that increased investment in one behaviour, such as survival of infection, leads to a decreased investment in another behaviour such as reproduction. This is because of the assumption that resources are limited and that those resources invested in reproduction cannot be invested for survival of infection (stearn 1989 1992 form haave audet). As a result, the evolution of resistance is constrained by overall fitness, with trade-offs arising between survival mechanisms, e.g. immune system, and other fitness-related traits such as reproductive success.
The extent and direction of these trade-offs can be environment-dependent, showing the importance of GxE in causing genetic variation (reference). A negative covariance (for example, high survival and low reproduction) between trait values would indicate a trade-off (reference). Yet multiple studies have found positive covariances (for example, high survival and high reproduction) when genetic trade-offs were expected (reference change Haave audet2022). However, a positive covariance does not mean that there is no genetic trade-off. As mentioned earlier, the trade-off model assumes that resources are limited, and cannot be shared between different fitness-related traits (reference in haave). Even if there is a trade-off on a genetic level for resource allocation, it could be masked on a phenotypic level by variation in resource acquisition (van noordwijk de jong 1986?maybe reznick super fleas). One way to think about this is with the “the big house, big car”  analogy: individuals with more resources (acquisition) can afford both a big house and a big car unlike an individual with fewer resources. There is still a trade-off, because the individuals with more resources cannot spend the same resources on both the big house and the big car, but it is less apparent than with those individuals with fewer resources (reference).  Van Noordwijk and de Jong first hypothesized that these positive covariance can come from genetic variation for resource acquisition and allocation of resources (van noordwijk de jong 1986). Furthermore, also in resource acquisition, there is different expression depending on environmental conditions (reference). This all highlights how complex the relationship is between genetic factors and environmental variation to shape the phenotypic traits.

A possible strategy to undermine resistance development in H. amigera is by employing GxEs in the use of biopesticides. Changing and rotating environmental pressures, farmers can prevents selection on one genotype. A genotype selected for in one environmental condition might not be selected for in another environmental condition. However, modern agricultural practices have become increasingly homogenous with large scale monocultures (Wuest et al., 2021). This creates an environment where pests are exposed to the same selective pressure over time. Finding practical and appealing ways for farmers to incorporate environmental variation is crucial. A promising strategy for varying environmental conductions is by rotating biopesticide doses instead of having a constant level. Higher doses generally lead to higher mortality, but low doses like sublethal doses have shown to lead to reduced fitness, including lower reproductive success and decreased food consumption (Wakil et al., 2022). Doses rotation might be a beneficial strategy for farmers, as it is easy to incorporate into already existing practices without having to create changes to crops or pesticide types.  

In my thesis, I aim to investigate the genetic trade-offs between pupal mass and survival in response to the rotation of biopesticide doses in Helicoverpa armigera. Pupal mass is an important indicator for overall fitness. It represents larval resource acquisition during pathogen infection, and it also serves as an important index for adult fitness, including reproductive success, because all resources used during the adult moth stage are acquired in the larval stage (find reference).  
	A negative covariance indicates a genetic trade-off, meaning that resources invested in one trait like survival come with a cost in the investment of resources in another trait like pupae mass. However a positive covariance does not directly rule out a genetic trade-off, there might be genetic variation in resource acquisition.
To test these hypotheses, I will use a half-sibling family experimental design in which some half-siblings from each family will be exposed to different doses of biopesticide. The between family variation reflects the additive genetic variation while the within-family variation reflects variation due to environmental and non-additive genetic factors (sarah via 1986). This approach will allow for an estimation of genetic correlations between the two traits and to detect a potential genetic trade-off under varying biopesticide doses. Furthermore, it can the type of covariances seen within families and different biopesticide dosage and between families in the same biopesticide dosage can also tell us something about resource acquisition in the case of positive covariances.
	Understanding the genetic relationship between those two traits under different biopesticide doses is critical for pesticide resistance management, because evolution of resistance is constrained by overall fitness. Rotating biopesticide doses creates different levels of environmental stress and can select for different genotypes, due to gene-by-environment interactions.

